### PR TITLE
Update htsjdk version

### PR DESCRIPTION
**Pull request by bbimber**
Note: I dont think I have permission to create branches in this repo, so I cant create a branch TeamCity will pick up. We could redirect this PR to a new branch on the LabKey side of the fork if you prefer, which should make tests run, right? I'd need a LK staff person to do this, I believe.

### CODE REVIEW

**Comment by labkey-tchad** [comment]
Verifying on TeamCity:
[OConnor Postgres](https://teamcity.labkey.org/buildConfiguration/LabKey_2111Release_Community_DailySuites_CustomModulesPostgres/1676474?showRootCauses=false&expandBuildChangesSection=true)
[OConnor SQL Server](https://teamcity.labkey.org/buildConfiguration/LabKey_2111Release_Community_DailySuites_CustomModulesSqlserver/1676472?showRootCauses=false&expandBuildChangesSection=true)
[SequenceAnalysis SQL Server](https://teamcity.labkey.org/buildConfiguration/LabKey_2111Release_Community_ExternalModulesTestSqlserver/1676476?showRootCauses=false)
[SequenceAnalysis Postgres](https://teamcity.labkey.org/buildConfiguration/LabKey_2111Release_Community_ExternalModulesTestPostgres/1676478?showRootCauses=false)

**Comment by labkey-tchad** [comment]
Failures look unrelated to this change. Genotyping (the other module that uses this dependency), seems happy.

**Review by labkey-jeckels — APPROVED** [review]

**Comment by bbimber** [comment]
@labkey-tchad @labkey-jeckels Thanks! 

How often do you merge 21.11-SNAPSHOT into develop? I'd like to merge my 21.11 branches forward, but I need changes sitting on release21.11-SNAPSHOT to compile.

**Comment by labkey-tchad** [comment]
@bbimber We merge forward once a week or so. We can merge this forward tomorrow after the dailies have verified everything.

**Pull request merged**
