### PR TITLE
Upgrade PostgreSQL, Microsoft SQL Server, and MySQL JDBC drivers

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
Everyone decided to upgrade

### CODE REVIEW

**Review by labkey-susanh — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
I was curious about the JRE 17 vs 11 for the SQL Server driver so I went to the MS page. It claims 11.2 is the latest.

https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?source=recommendations&view=sql-server-ver16

I don't see 12.2 listed in Maven either.

https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc

Is there some secret place for the newest releases?

**Comment by labkey-adam** [comment]
> I was curious about the JRE 17 vs 11 for the SQL Server driver so I went to the MS page. It claims 11.2 is the latest.
> 
> https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?source=recommendations&view=sql-server-ver16
> 
> I don't see 12.2 listed in Maven either.
> 
> https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
> 
> Is there some secret place for the newest releases?

It shows up in the new Maven UI: https://central.sonatype.com/artifact/com.microsoft.sqlserver/mssql-jdbc/12.2.0.jre11

SQL Server team were nice enough to give me a heads up that they were releasing, since I reported that SQLException bug to them

I'm not planning to merge until they officially announce and provide release notes, but it's close enough to get some test coverage

**Comment by labkey-adam** [comment]
> > I was curious about the JRE 17 vs 11 for the SQL Server driver so I went to the MS page. It claims 11.2 is the latest.
> > https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?source=recommendations&view=sql-server-ver16
> > I don't see 12.2 listed in Maven either.
> > https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc
> > Is there some secret place for the newest releases?
> 
> It shows up in the new Maven UI: https://central.sonatype.com/artifact/com.microsoft.sqlserver/mssql-jdbc/12.2.0.jre11
> 
> SQL Server team were nice enough to give me a heads up that they were releasing, since I reported that SQLException bug to them
> 
> I'm not planning to merge until they officially announce and provide release notes, but it's close enough to get some test coverage

Download page and release notes have been updated: https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16

**Comment by labkey-adam** [comment]
https://techcommunity.microsoft.com/t5/sql-server-blog/jdbc-driver-12-2-for-sql-server-released/ba-p/3731398

**Pull request merged**
