### PR TITLE
 Issue 41874: Fix distribution file names to make version clear

### PR DESCRIPTION
**Pull request by labkey-tchad**
#### Rationale
[Issue 41874: Update distribution naming](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=41874)

#### Related Pull Requests
* https://github.com/LabKey/gradlePlugin/pull/102

### CODE REVIEW

**Review by labkey-adam — APPROVED** [review]

**Review by labkey-susanh — COMMENTED** [review]
Do we need to pull it into 20.11-SNAPSHOT in order to test the distribution naming or can we test in your fb_buildNumber branch and then release the plugin and then merge with the released plugin version?

**Comment by labkey-jony** [comment]
FYI - This file change is going to require me to rewrite the Push Downloads Lambda job again.

Previously, the old push script and the new Push Downloads portal used the word "bin" as a way to identify the split between the name of the binaries and their respective extensions.

I had to make some modifications to anticipate the dash, the name of the client distro, and the dot for the rest of it. This additional dash is going to further complicate things.

**Comment by labkey-tchad** [comment]
@labkey-susanh I verified with the feature branch here: https://teamcity.labkey.org/buildConfiguration/LabKey_2011Release_Internal_InstallerCustom/1176979?buildTab=artifacts

**Comment by labkey-tchad** [comment]
@labkey-jony I just opened a PR to handle all of the various names we have across different versions. https://github.com/LabKey/pushdownloads/pull/12

**Pull request merged**
