### PR TITLE
Issue 37040: Test Microsoft JDBC driver for SQL Server

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
The official Microsoft JDBC driver has some nice capabilities beyond jTDS, including higher availability.

#### Related Pull Requests
* https://github.com/LabKey/platform/pull/3440

#### Changes
* Update properties
* Make MS driver the default choice via pickMsSql

### CODE REVIEW

**Review by labkey-susanh — COMMENTED** [review]
Is there value in adding a pickSqlServer Gradle task as well?  It could be easily added via a new gradlePlugin release or added directly into the `server/build.gradle` file.

**Comment by labkey-jeckels** [comment]
> Is there value in adding a pickSqlServer Gradle task as well? It could be easily added via a new gradlePlugin release or added directly into the `server/build.gradle` file.

@labkey-susanh that sounds nice while we're supporting both. Maybe we should call it pickJTDS/jtds.properties instead?

**Review by labkey-tchad — APPROVED** [review]
I like the idea of changing it to `jtds.properties`. Either way works for TeamCity though.

**Comment by labkey-susanh** [comment]
> I like the idea of changing it to `jtds.properties`. Either way works for TeamCity though.

👍

**Comment by labkey-susanh** [comment]
> > Is there value in adding a pickSqlServer Gradle task as well? It could be easily added via a new gradlePlugin release or added directly into the `server/build.gradle` file.
> 
> @labkey-susanh that sounds nice while we're supporting both. Maybe we should call it pickJTDS/jtds.properties instead?

@labkey-jeckels Do you want to do the gradlePlugin update or do you want to me do it?

**Comment by labkey-tchad** [comment]
> @labkey-jeckels Do you want to do the gradlePlugin update or do you want me to do it?

I'll do it. Seems like an easy change to make wile waiting for my build to finish.

**Comment by labkey-tchad** [comment]
https://github.com/LabKey/gradlePlugin/pull/149

**Pull request merged**
