### PR TITLE
Bump Log4J to 2.18.0 with fixes to work with embedded Tomcat

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
We want the latest Log4J, but only if it also works with embedded Tomcat and Spring Boot.

#### Changes
* Bump to 2.18.0
* Filter out Spring Boot-specific config files to avoid confusing the copy of Log4J inside of the webapp

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@labkey-susanh I couldn't figure out how to get embedded Tomcat to also use 2.18.0. I tried copying the resolutionStrategy section of the main server build.gradle into the embedded file but must have been doing something wrong.

The mismatch works fine because they're separate classloaders but I assume we want to align regardless.

**Comment by labkey-jeckels** [comment]
@labkey-tchad can you help me find the right suites to kick off a validation of embedded Tomcat on this FB?

**Comment by labkey-tchad** [comment]
> @labkey-susanh I couldn't figure out how to get embedded Tomcat to also use 2.18.0. I tried copying the resolutionStrategy section of the main server build.gradle into the embedded file but must have been doing something wrong.
> 
> The mismatch works fine because they're separate classloaders but I assume we want to align regardless.

I figured out how to set the log4j version the last time around. Just pulled it off my shelf.

**Comment by labkey-tchad** [comment]
> 

It's already queued. TeamCity runs the [embedded Sample Manager suite](https://teamcity.labkey.org/buildConfiguration/LabKey_Trunk_Internal_Embedded_SampleManagerEmbeddedPostgres?mode=branches) with any changes to `server/embedded`.

**Review by labkey-adam — APPROVED** [review]

**Review by labkey-tchad — APPROVED** [review]
Embedded suite looks happy

**Review by labkey-susanh — APPROVED** [review]

**Pull request merged**
